[package]
authors = ["Brenden Matthews <brenden@brndn.io>"]
description = "dryoc is a pure-Rust implementation of the excellent libsodium"
documentation = "https://docs.rs/dryoc"
edition = "2018"
license = "LGPL-3.0-only"
name = "dryoc"
readme = "README.md"
repository = "https://github.com/brndnmtthws/dryoc"
rust = "1.51"
version = "0.3.0"

[dependencies]
base64 = {version = "0.13", optional = true}
bitflags = "1.0"
chacha20 = {version = "0.6", features = ["rng"]}
curve25519-dalek = "3.0"
generic-array = "0.14"
rand_core = {version = "0.5", features = ["getrandom"]}
salsa20 = {version = "0.7", features = ["hsalsa20"]}
serde = {version = "1.0", optional = true, features = ["derive"]}
sha2 = "0.9"
subtle = "2.4"
x25519-dalek = "1.1"
zeroize = "1"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["minwindef", "memoryapi", "sysinfoapi", "impl-default"]}

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
base64 = "0.13"
libc = "0.2"
libsodium-sys = "0.2"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
sodiumoxide = "0.2"
static_assertions = "0.1"

[features]
default = [
  "u64_backend",
]
nightly = []
simd_backend = ["curve25519-dalek/simd_backend", "sha2/asm"]
u32_backend = ["x25519-dalek/u32_backend"]
u64_backend = ["x25519-dalek/u64_backend"]
