[package]
authors = ["Brenden Matthews <brenden@brndn.io>"]
description = "dryoc is a pure-Rust implementation of the excellent libsodium"
edition = "2018"
license = "LGPL-3.0-only"
name = "dryoc"
readme = "README.md"
version = "0.2.0"

[dependencies]
base64 = {version = "0.13", optional = true}
curve25519-dalek = "3.0"
generic-array = "0.14"
poly1305 = "0.6"
rand_core = {version = "0.5", features = ["getrandom"]}
salsa20 = {version = "0.7", features = ["hsalsa20"]}
serde = {version = "*", optional = true, features = ["derive"]}
sha2 = "0.9"
subtle = "2.4"
x25519-dalek = "1.1"
zeroize = "1.2"

[dev-dependencies]
base64 = "0.13"
serde_json = "*"
sodiumoxide = "0.2"

[features]
default = [
  "u64_backend",
]
simd_backend = ["curve25519-dalek/simd_backend"]
u32_backend = ["x25519-dalek/u32_backend"]
u64_backend = ["x25519-dalek/u64_backend"]
